"use client";

import { useState } from 'react';
import * as XLSX from 'xlsx';
import { UploadCloud, CheckCircle2, AlertCircle, FileSpreadsheet, Loader2, ArrowRight } from 'lucide-react';
import { bulkImportLeads } from '../actions';
import { useRouter } from 'next/navigation';

export default function BulkImportPage() {
  const [file, setFile] = useState(null);
  const [previewData, setPreviewData] = useState([]);
  const [isDragging, setIsDragging] = useState(false);
  const [isImporting, setIsImporting] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);
  const router = useRouter();

  const handleFileUpload = (e) => {
    const uploadedFile = e.target.files?.[0] || e.dataTransfer?.files?.[0];
    if (!uploadedFile) return;

    if (!uploadedFile.name.endsWith('.xlsx') && !uploadedFile.name.endsWith('.xls') && !uploadedFile.name.endsWith('.csv')) {
      setError("Please upload a valid Excel (.xlsx, .xls) or CSV file.");
      return;
    }

    setFile(uploadedFile);
    setError(null);
    setSuccess(false);

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const data = new Uint8Array(event.target.result);
        const workbook = XLSX.read(data, { type: 'array' });
        const firstSheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[firstSheetName];
        const json = XLSX.utils.sheet_to_json(worksheet);
        setPreviewData(json);
      } catch (err) {
        setError("Could not parse the file. Ensure it's a valid Excel or CSV.");
      }
    };
    reader.readAsArrayBuffer(uploadedFile);
  };

  const confirmImport = async () => {
    if (previewData.length === 0) return;
    setIsImporting(true);
    setError(null);

    try {
      // Ensure data is completely stripped of any XLSX prototype methods before sending to Server Action
      const plainData = JSON.parse(JSON.stringify(previewData));
      await bulkImportLeads(plainData);
      setSuccess(true);
      setTimeout(() => {
        router.push('/admin');
      }, 2000);
    } catch (err) {
      console.error(err);
      setError("Failed to import leads. Please try again.");
    } finally {
      setIsImporting(false);
    }
  };

  return (
    <div className="min-h-full bg-slate-50 p-6 sm:p-10 font-sans">
      <div className="max-w-[1400px] mx-auto space-y-8">
        <header className="mb-10">
          <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight mb-2">Bulk Import</h1>
          <p className="text-slate-500 font-medium">Upload an Excel or CSV file generated by Gemini to instantly create leads.</p>
        </header>

      {!file && (
        <div 
          className={`border-2 border-dashed rounded-xl p-16 text-center transition-all bg-white
            ${isDragging ? 'border-slate-900 bg-slate-50' : 'border-slate-200 hover:border-slate-300'}
          `}
          onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
          onDragLeave={() => setIsDragging(false)}
          onDrop={(e) => { e.preventDefault(); setIsDragging(false); handleFileUpload(e); }}
        >
          <div className="w-16 h-16 bg-slate-50 text-slate-400 rounded-xl flex items-center justify-center mx-auto mb-6 border border-slate-200">
            <UploadCloud size={24} strokeWidth={2} />
          </div>
          <h3 className="text-xl font-bold text-slate-900 mb-2">Upload your dataset</h3>
          <p className="text-slate-500 mb-8 max-w-sm mx-auto font-medium leading-relaxed">Drag and drop your .xlsx or .csv file here, or click to browse your computer.</p>
          
          <label className="inline-flex items-center justify-center px-6 py-2.5 text-sm font-medium text-white bg-slate-900 rounded-md hover:bg-slate-800 cursor-pointer transition-colors shadow-sm">
            Browse Files
            <input type="file" className="hidden" accept=".xlsx,.xls,.csv" onChange={handleFileUpload} />
          </label>
          
          <div className="mt-10 pt-8 border-t border-slate-100/60 text-[11px] font-bold uppercase tracking-wider text-slate-400 flex items-center justify-center gap-2">
            <FileSpreadsheet size={16} /> Requires columns: Clinic Name, Email, Phone, Doctor Name, Address
          </div>
        </div>
      )}

      {error && (
        <div className="p-4 bg-red-50/50 border border-red-100 rounded-2xl text-red-600 flex items-center gap-3 mb-8 shadow-sm">
          <AlertCircle size={20} />
          <span className="font-medium text-sm">{error}</span>
        </div>
      )}

      {success && (
        <div className="p-6 bg-emerald-50/50 border border-emerald-100 rounded-2xl text-emerald-700 flex items-center gap-4 mb-8 shadow-sm animate-in fade-in slide-in-from-bottom-4">
          <div className="w-10 h-10 bg-emerald-100 rounded-full flex items-center justify-center shrink-0">
            <CheckCircle2 size={24} className="text-emerald-600" />
          </div>
          <div>
            <h4 className="font-bold text-emerald-800">Import Successful!</h4>
            <p className="text-emerald-600/80 mt-0.5 text-sm font-medium">Your leads have been added. Redirecting to dashboard...</p>
          </div>
        </div>
      )}

      {file && previewData.length > 0 && !success && (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-4 border-b border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between bg-slate-50 gap-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-white border border-slate-200 text-slate-600 rounded-lg flex items-center justify-center shadow-sm">
                <FileSpreadsheet size={20} />
              </div>
              <div>
                <h3 className="font-bold text-slate-900 text-lg">Previewing {previewData.length} Leads</h3>
                <p className="text-sm text-slate-500 font-medium">{file.name}</p>
              </div>
            </div>
            
            <div className="flex gap-3">
              <button 
                onClick={() => { setFile(null); setPreviewData([]); }}
                className="px-4 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-200 rounded-md hover:bg-slate-50 hover:text-slate-900 transition-colors shadow-sm"
                disabled={isImporting}
              >
                Cancel
              </button>
              <button 
                onClick={confirmImport}
                disabled={isImporting}
                className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-slate-900 rounded-md hover:bg-slate-800 transition-colors shadow-sm disabled:opacity-70 disabled:cursor-not-allowed"
              >
                {isImporting ? (
                  <><Loader2 size={18} className="animate-spin" /> Importing...</>
                ) : (
                  <>Import {previewData.length} Leads <ArrowRight size={18} /></>
                )}
              </button>
            </div>
          </div>

          <div className="overflow-x-auto max-h-[500px]">
            <table className="w-full text-left text-sm whitespace-nowrap">
              <thead className="bg-white sticky top-0 z-10 shadow-sm">
                <tr>
                  <th className="px-6 py-5 text-[10px] uppercase tracking-wider font-bold text-slate-400 border-b border-slate-100">Clinic Name</th>
                  <th className="px-6 py-5 text-[10px] uppercase tracking-wider font-bold text-slate-400 border-b border-slate-100">Doctor Name</th>
                  <th className="px-6 py-5 text-[10px] uppercase tracking-wider font-bold text-slate-400 border-b border-slate-100">Email</th>
                  <th className="px-6 py-5 text-[10px] uppercase tracking-wider font-bold text-slate-400 border-b border-slate-100">Phone</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {previewData.slice(0, 15).map((row, i) => (
                  <tr key={i} className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-6 py-4 font-bold text-slate-900">{row['Clinic Name'] || <span className="text-slate-300 italic font-normal">Empty</span>}</td>
                    <td className="px-6 py-4 font-medium text-slate-700">{row['Doctor Name'] || <span className="text-slate-300 italic font-normal">-</span>}</td>
                    <td className="px-6 py-4 text-blue-600 font-medium">{row['Email'] || row['Public Email'] || <span className="text-slate-300 italic font-normal">-</span>}</td>
                    <td className="px-6 py-4 font-medium text-slate-700">{row['Phone'] || row['Phone Number'] || <span className="text-slate-300 italic font-normal">-</span>}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {previewData.length > 15 && (
              <div className="p-4 text-center text-xs font-bold uppercase tracking-wider text-slate-400 bg-slate-50 border-t border-slate-100">
                Showing first 15 of {previewData.length} rows...
              </div>
            )}
          </div>
        </div>
      )}
      </div>
    </div>
  );
}
